// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.5
// source: proto/blod.proto

package blodBank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_proto_blod_proto_rawDescGZIP(), []int{0}
}

// System Service
type SystemStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_proto_blod_proto_rawDescGZIP(), []int{1}
}

func (x *SystemStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewDonor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BlodType string `protobuf:"bytes,2,opt,name=blod_type,json=blodType,proto3" json:"blod_type,omitempty"`
}

func (x *NewDonor) Reset() {
	*x = NewDonor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDonor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDonor) ProtoMessage() {}

func (x *NewDonor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDonor.ProtoReflect.Descriptor instead.
func (*NewDonor) Descriptor() ([]byte, []int) {
	return file_proto_blod_proto_rawDescGZIP(), []int{2}
}

func (x *NewDonor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewDonor) GetBlodType() string {
	if x != nil {
		return x.BlodType
	}
	return ""
}

type DonorID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DonorID) Reset() {
	*x = DonorID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonorID) ProtoMessage() {}

func (x *DonorID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonorID.ProtoReflect.Descriptor instead.
func (*DonorID) Descriptor() ([]byte, []int) {
	return file_proto_blod_proto_rawDescGZIP(), []int{3}
}

func (x *DonorID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DonorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BlodType string `protobuf:"bytes,3,opt,name=blod_type,json=blodType,proto3" json:"blod_type,omitempty"`
}

func (x *DonorInfo) Reset() {
	*x = DonorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonorInfo) ProtoMessage() {}

func (x *DonorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonorInfo.ProtoReflect.Descriptor instead.
func (*DonorInfo) Descriptor() ([]byte, []int) {
	return file_proto_blod_proto_rawDescGZIP(), []int{4}
}

func (x *DonorInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DonorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DonorInfo) GetBlodType() string {
	if x != nil {
		return x.BlodType
	}
	return ""
}

type DonorList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donors []*DonorInfo `protobuf:"bytes,1,rep,name=donors,proto3" json:"donors,omitempty"`
}

func (x *DonorList) Reset() {
	*x = DonorList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blod_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonorList) ProtoMessage() {}

func (x *DonorList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blod_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonorList.ProtoReflect.Descriptor instead.
func (*DonorList) Descriptor() ([]byte, []int) {
	return file_proto_blod_proto_rawDescGZIP(), []int{5}
}

func (x *DonorList) GetDonors() []*DonorInfo {
	if x != nil {
		return x.Donors
	}
	return nil
}

var File_proto_blod_proto protoreflect.FileDescriptor

var file_proto_blod_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x22, 0x09, 0x0a, 0x07,
	0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x3b, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x19,
	0x0a, 0x07, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x09, 0x44, 0x6f, 0x6e,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x6c, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x38, 0x0a, 0x09, 0x44, 0x6f, 0x6e, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e,
	0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x64, 0x6f, 0x6e, 0x6f, 0x72,
	0x73, 0x32, 0x42, 0x0a, 0x0d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x62, 0x6c, 0x6f,
	0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x16, 0x2e,
	0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xb2, 0x01, 0x0a, 0x0c, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x12, 0x12, 0x2e, 0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61,
	0x6e, 0x6b, 0x2e, 0x4e, 0x65, 0x77, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x1a, 0x11, 0x2e, 0x62, 0x6c,
	0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x32,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x12, 0x11, 0x2e, 0x62, 0x6c, 0x6f,
	0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x44, 0x1a, 0x13, 0x2e,
	0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x6e, 0x6f,
	0x72, 0x73, 0x12, 0x11, 0x2e, 0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x2e, 0x4e, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x13, 0x2e, 0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b,
	0x2e, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x62, 0x6c, 0x6f, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_blod_proto_rawDescOnce sync.Once
	file_proto_blod_proto_rawDescData = file_proto_blod_proto_rawDesc
)

func file_proto_blod_proto_rawDescGZIP() []byte {
	file_proto_blod_proto_rawDescOnce.Do(func() {
		file_proto_blod_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_blod_proto_rawDescData)
	})
	return file_proto_blod_proto_rawDescData
}

var file_proto_blod_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_blod_proto_goTypes = []interface{}{
	(*NoParam)(nil),      // 0: blodBank.NoParam
	(*SystemStatus)(nil), // 1: blodBank.SystemStatus
	(*NewDonor)(nil),     // 2: blodBank.NewDonor
	(*DonorID)(nil),      // 3: blodBank.DonorID
	(*DonorInfo)(nil),    // 4: blodBank.DonorInfo
	(*DonorList)(nil),    // 5: blodBank.DonorList
}
var file_proto_blod_proto_depIdxs = []int32{
	4, // 0: blodBank.DonorList.donors:type_name -> blodBank.DonorInfo
	0, // 1: blodBank.SystemService.Ping:input_type -> blodBank.NoParam
	2, // 2: blodBank.DonorService.RegisterDonor:input_type -> blodBank.NewDonor
	3, // 3: blodBank.DonorService.GetDonor:input_type -> blodBank.DonorID
	0, // 4: blodBank.DonorService.GetAllDonors:input_type -> blodBank.NoParam
	1, // 5: blodBank.SystemService.Ping:output_type -> blodBank.SystemStatus
	3, // 6: blodBank.DonorService.RegisterDonor:output_type -> blodBank.DonorID
	4, // 7: blodBank.DonorService.GetDonor:output_type -> blodBank.DonorInfo
	5, // 8: blodBank.DonorService.GetAllDonors:output_type -> blodBank.DonorList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_blod_proto_init() }
func file_proto_blod_proto_init() {
	if File_proto_blod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_blod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDonor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonorID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blod_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonorList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_blod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_blod_proto_goTypes,
		DependencyIndexes: file_proto_blod_proto_depIdxs,
		MessageInfos:      file_proto_blod_proto_msgTypes,
	}.Build()
	File_proto_blod_proto = out.File
	file_proto_blod_proto_rawDesc = nil
	file_proto_blod_proto_goTypes = nil
	file_proto_blod_proto_depIdxs = nil
}
